# Generated by Django 4.0.5 on 2022-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(to='achievements.achievement'),
        ),
    ]
