# Generated by Django 4.0.5 on 2022-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('users', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, to='achievements.achievement'),
        ),
    ]
